### ISSUE TITLE
No error in variable declaration

### ISSUE THREAD

**Issue by jldav1d** [remoo69/Compiler-Sheesh#10]
### **As a group na itong error, applicable to any data type**

**Expected:** Unexpected <data_type> at line 2, expected Identifier
**Actual Result:** Invalid Delimiter for Keyword 'dec', ')'  

For example
```
sheesh(){
    dec dec = 12.34 + 6.5# 
    up("$d", dec)# 
} 
```

**Comment by remoo69** [comment]
case 1:
![image](https://github.com/remoo69/Compiler-Sheesh/assets/121857724/91e8dc1e-8205-4292-bb63-dbf3d64db68d)

case 2:
![image](https://github.com/remoo69/Compiler-Sheesh/assets/121857724/f9196609-f00f-467a-9a3c-94ce6e8c4cfd)
