### ISSUE TITLE
No error when "..." is missing

### ISSUE THREAD

**Issue by jldav1d** [remoo69/Compiler-Sheesh#11]
**Expected Error:** missing concat
```
sheesh(){
    text yoyo = "yes" "yeah"# 
    up("$t", yoyo)#
}
```

**Comment by jldav1d** [comment]
syntax

**Comment by remoo69** [comment]
![image](https://github.com/remoo69/Compiler-Sheesh/assets/121857724/57028c92-7660-4783-a132-6723fafae4ac)
correctly identifies error but semi-wrong expected set.
