### ISSUE TITLE
Error with function invocation

### ISSUE THREAD

**Issue by jldav1d** [remoo69/Compiler-Sheesh#14]
**Error Message:** Unexpected Identifier at line 2, expected sus
**Expected:** No Error

Mostly nagraraise yung message na to with function invocation

For example:
```
sheesh(){
    up(" ")#
}
```

**Comment by remoo69** [comment]
![image](https://github.com/remoo69/Compiler-Sheesh/assets/121857724/9854e77b-9a43-4e34-ba08-beb1a38280f1)
unresolved. produces proper output when "a". might be a tokenization issue
