### ISSUE TITLE
expected sheesh at line 1

### ISSUE THREAD

**Issue by 1202DREAMSCAPE** [remoo69/Compiler-Sheesh#2]
**Any line of code located at line 1** except for sheesh(){ invokes error.

_**CASE 1**_

<img width="423" alt="image" src="https://github.com/remoo69/Compiler-Sheesh/assets/88035813/563b4ceb-2065-470c-a614-6d2b2d86678c">

_**CASE 2**_

<img width="312" alt="image" src="https://github.com/remoo69/Compiler-Sheesh/assets/88035813/191d457e-f5e7-49ea-8d1b-04220deaa0b4">

**Comment by 1202DREAMSCAPE** [comment]
✅ works with use

<img width="941" alt="image" src="https://github.com/remoo69/Compiler-Sheesh/assets/88035813/58ae2fd3-fda3-43b2-b510-cc16b535fc33">

**Comment by remoo69** [comment]
case 1: cfg ambiguity. see const_declaration and const_tail s
case 2: () is not in the cfg e. 

currently working on a solution

**Comment by remoo69** [comment]
fixed case 1!
