### ISSUE TITLE
Update has an impact to overall code

### ISSUE THREAD

**Issue by 1202DREAMSCAPE** [remoo69/Compiler-Sheesh#26]
![image](https://github.com/remoo69/Compiler-Sheesh/assets/88035813/ce9c50ee-016e-4a6e-8c6f-ce163a8c4fcc)

error will be fixed if there is an absence of newline (one line lang lahat)

**Comment by remoo69** [comment]
This is noted

**Comment by remoo69** [comment]
aalisin ko nalang sa final display ng tokens
