### ISSUE TITLE
issue na nakita ko

### ISSUE THREAD

**Issue by Vivamusmagna** [remoo69/Compiler-Sheesh#28]
![1](https://github.com/remoo69/Compiler-Sheesh/assets/148524793/6dcdbc67-ffcd-41d9-8359-8f964229361c)

**Comment by Vivamusmagna** [comment]
![2](https://github.com/remoo69/Compiler-Sheesh/assets/148524793/e5bf3f5e-91ee-4fa2-bef1-019834c72d46)

**Comment by Vivamusmagna** [comment]
![Uploading 3.jpg…]()

**Comment by Vivamusmagna** [comment]
![3](https://github.com/remoo69/Compiler-Sheesh/assets/148524793/782dac2d-21c7-4dbc-9c40-0ec7ce7ea45f)

**Comment by Vivamusmagna** [comment]
![3](https://github.com/remoo69/Compiler-Sheesh/assets/148524793/25935a1e-dfce-447b-98bf-927e68bf2f81)

**Comment by Vivamusmagna** [comment]
![4](https://github.com/remoo69/Compiler-Sheesh/assets/148524793/6e207072-a73c-4ad4-838f-764cc68ba396)

**Comment by Vivamusmagna** [comment]
![5](https://github.com/remoo69/Compiler-Sheesh/assets/148524793/19f3079b-eff8-42dd-b3a6-72691e01d331)

**Comment by remoo69** [comment]
> ![2](https://private-user-images.githubusercontent.com/148524793/321663335-e5bf3f5e-91ee-4fa2-bef1-019834c72d46.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4ODE3MTksIm5iZiI6MTcxMjg4MTQxOSwicGF0aCI6Ii8xNDg1MjQ3OTMvMzIxNjYzMzM1LWU1YmYzZjVlLTkxZWUtNGZhMi1iZWYxLTAxOTgzNGM3MmQ0Ni5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMlQwMDIzMzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNWI1NjNhMDk1OWI3YTljYjdkMzYzNTNkNzM4ZDU0OWUyZWQ2OTg5NjU1MzIzMmYxODMwYzRhMjAzMDZmZmQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UJArJUr5mMwlCoh7FE1Etf9LX6Qbf3m-QAU2Y7FKyLU)
> 
> I think may problem sa newline pag nakaayos sa string and dun sa mga statements sa functions

pre wala atang # yung statements dun sa func

**Comment by remoo69** [comment]
> ![5](https://private-user-images.githubusercontent.com/148524793/321671898-19f3079b-eff8-42dd-b3a6-72691e01d331.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4ODE3MTksIm5iZiI6MTcxMjg4MTQxOSwicGF0aCI6Ii8xNDg1MjQ3OTMvMzIxNjcxODk4LTE5ZjMwNzliLWVmZjgtNDJkZC1iM2E2LTcyNjkxZTAxZDMzMS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMlQwMDIzMzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMWMzNGE2Y2M1MWYxMDQxYTNmMDE0MzY0ODI5OTk3NDhmYTFiMDNhOWE5OTEwMmQ3NjUyYTdiZmUyOTVjNDE3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.c8vyQFAdXJBBLW1mVMtrZc8HgzweUDvgfEGRBlFWXEU)

sobra sa zeroes yan pre kaya di tokenized

**Comment by Vivamusmagna** [comment]
![6](https://github.com/remoo69/Compiler-Sheesh/assets/148524793/7b82c67c-0aee-47f6-9bdb-f5535556636c)

wala ba ganitong condition sa whilst?

**Comment by Vivamusmagna** [comment]
![7](https://github.com/remoo69/Compiler-Sheesh/assets/148524793/acd307a5-5de2-4212-bf85-b36cabd62758)

I think yung error na ito may problem sa comments bawal sa labas ng sheesh main....

**Comment by Vivamusmagna** [comment]
![8](https://github.com/remoo69/Compiler-Sheesh/assets/148524793/cc4931e4-45d9-48c1-a747-494cc26b308e)


ang weird man

**Comment by Vivamusmagna** [comment]
yung iba alam ko same error pero nilalagay ko lng for documentation para alam ko din san sa 150 yung may errors

**Comment by Vivamusmagna** [comment]
![9](https://github.com/remoo69/Compiler-Sheesh/assets/148524793/d18bb606-0c67-4c47-b221-e1f100e333a1)

pre error sa multiple declaration

**Comment by jldav1d** [comment]
> ![3](https://private-user-images.githubusercontent.com/148524793/321667078-25935a1e-dfce-447b-98bf-927e68bf2f81.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5MTU1ODcsIm5iZiI6MTcxMjkxNTI4NywicGF0aCI6Ii8xNDg1MjQ3OTMvMzIxNjY3MDc4LTI1OTM1YTFlLWRmY2UtNDQ3Yi05OGJmLTkyN2U2OGJmMmY4MS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMlQwOTQ4MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZGU0NTM1MjFkMTNhN2RkODdkZjUxMmU0MzgwMTY0NzFhYWVmOWE2MTFiMzQ2ODJkNDI1NDQ1NDg5MjlkNDY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MNrJJLbr-KHnkE98KZ_Pyn_mxsyWPGmEiyvaOYpTkgs)

sobra na sa 30 characters yung function name na yan haha

**Comment by remoo69** [comment]
> ![2](https://private-user-images.githubusercontent.com/148524793/321663335-e5bf3f5e-91ee-4fa2-bef1-019834c72d46.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5ODIzMDAsIm5iZiI6MTcxMjk4MjAwMCwicGF0aCI6Ii8xNDg1MjQ3OTMvMzIxNjYzMzM1LWU1YmYzZjVlLTkxZWUtNGZhMi1iZWYxLTAxOTgzNGM3MmQ0Ni5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxM1QwNDIwMDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZGIxZjNmMGEzZDA3ZmExOGM3NzdhZDUzZWZhZjFhOGNmMWJhMWU3ODgyYmUyYmMwZDI1NWEzZTZhMjE0MTU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ENzaixxrovwiUcw9VMs7_WmpykMM8HIRgJdfnizUOEw)
> 
> I think may problem sa newline pag nakaayos sa string and dun sa mga statements sa functions

bawal newline sa params or args natin

**Comment by remoo69** [comment]
> ![5](https://private-user-images.githubusercontent.com/148524793/321671898-19f3079b-eff8-42dd-b3a6-72691e01d331.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5ODIzMDAsIm5iZiI6MTcxMjk4MjAwMCwicGF0aCI6Ii8xNDg1MjQ3OTMvMzIxNjcxODk4LTE5ZjMwNzliLWVmZjgtNDJkZC1iM2E2LTcyNjkxZTAxZDMzMS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxM1QwNDIwMDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNTkyYWY2ODYyYzU5MzMxMDI2OWUzNTRlNzA4N2M3ODU1YmUxYWNiOGY4Y2Q3ZTk1MzQ0ZDAyMmIzZTJjOTFhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.fBZ0IAk7G97rfTgZdGUmJ8o_--i9aTN1DUrNPbKJKWI)

![image](https://github.com/remoo69/Compiler-Sheesh/assets/121857724/57ade1d0-d23b-4ce0-8671-14998f9589f8)
pwede naman natin taasan kung gusto nyo. sa tingin ko din medj restrictive yung 32k max lang? @Vivamusmagna @jldav1d

**Comment by remoo69** [comment]
close ko na to
