### ISSUE TITLE
parsing issue when there is no closing parenthesis or square bracket

### ISSUE THREAD

**Issue by jldav1d** [remoo69/Compiler-Sheesh#29]
_**Expected**: Error no closing parenthesis
**Actual**: No Syntax Error_

Sample code:
```
sheesh(){
	whole x = (10#
	whole n = (id(#
	whole i = id[ #
}
```

**Comment by remoo69** [comment]
![image](https://github.com/remoo69/Compiler-Sheesh/assets/121857724/24506a25-8dfb-4cd9-90b0-1e294190adc4)
unenforced pala yung )
