### ISSUE TITLE
comment tokens gone?

### ISSUE THREAD

**Issue by 1202DREAMSCAPE** [remoo69/Compiler-Sheesh#3]
inline and block comments arent visible as tokens anymore, ganito ba talaga siya? even for our lexical? i remember kasi na we had mga 2 pulls ago HAHAHAHA

<img width="938" alt="image" src="https://github.com/remoo69/Compiler-Sheesh/assets/88035813/d2cb1f14-7afb-4c01-91f9-2a3c047a9663">

**Comment by remoo69** [comment]
oh may filter atm that removes them para sa syntax. tanggalin ko nalang for lex then reimplement for syntax
