### ISSUE TITLE
not parsing when declaring a sus

### ISSUE THREAD

**Issue by jldav1d** [remoo69/Compiler-Sheesh#30]
Code:
```
sheesh(){
    sus x = cap#
}
```
Terminal Message:
![image](https://github.com/remoo69/Compiler-Sheesh/assets/92510338/769940a0-9f19-4609-8e28-e15b347feffa)

**Comment by remoo69** [comment]
![image](https://github.com/remoo69/Compiler-Sheesh/assets/121857724/6318c9cb-5003-4e25-8bf3-ac47f27e07be)
wala ulit () yung func HAHAHAAHAHAHAH
