### ISSUE TITLE
issue with return value using yeet

### ISSUE THREAD

**Issue by jldav1d** [remoo69/Compiler-Sheesh#31]
**Expected:** No error
**Error Message:**
_Syntax Error:
Line 2, Token 2: Unexpected "10" [Whole], expected -> ['#']_ 

Code:
```
def whole func(){
    yeet 10#
}
sheesh(){
    whole x = 0#
}
```

**Comment by remoo69** [comment]
![image](https://github.com/remoo69/Compiler-Sheesh/assets/121857724/d0caee19-1e69-4e17-acb6-4a060d6a354b)
naiirita ako sa cause ng error, walang () yung return val pati yung literal_or_expr
