### ISSUE TITLE
Issue with parenthesis in expressions

### ISSUE THREAD

**Issue by jldav1d** [remoo69/Compiler-Sheesh#32]
May ambiguity siguro sa literal_or_expr concerning sa parenthesis

**Sample code:**
1.)
```
sheesh(){
    x = (1 + 1 + 1)#
}
```
**Expected:** No Error
**Actual:**
_Syntax Error:
Line 2, Token 4: Unexpected "1" [Whole], expected -> ['Identifier', '(', ')']_

2.)
```
sheesh(){
    x = 1 + 1 + 1#
}
```
**Expected:** No Error
**Actual:** No Error

**Comment by remoo69** [comment]
gets ko na, ambiguity sa idvalparen

**Comment by remoo69** [comment]
Output:
![image](https://github.com/remoo69/Compiler-Sheesh/assets/121857724/9e3ad311-9558-42d1-b471-73926003a524)

**Comment by remoo69** [comment]
di ko muna close yung issue kasi baka mamaya may repercussion yung removal ng idvalparen

**Comment by jldav1d** [comment]
oki, mag-test pa ko ng expressions to check if gucci na

**Comment by remoo69** [comment]
close ko na to
