### ISSUE TITLE
Newlines or comment before sheesh()

### ISSUE THREAD

**Issue by jldav1d** [remoo69/Compiler-Sheesh#33]
Not sure if ano dapat expected result for having a newline before sheesh, but tingin ko dapat valid naman

Code:
1.)
```
- newline
- newline
sheesh(){
    whole x = 10#
}
```
2.)
```
//newline
sheesh(){
    whole x = 10#
}
```
For this dapat walang error
**_Error Message_**:
Syntax Error:
Line 1, Token 2: Unexpected "EOL" [Newline], expected -> ['text', 'sus', 'use', 'dec', 'based', 'sheesh', 'whole', 'charr', 'def']

**Comment by jldav1d** [comment]
same pala to sa dalawang issues ni greg

**Comment by remoo69** [comment]
issue solved
