### ISSUE TITLE
Not tokenizing '\0' character

### ISSUE THREAD

**Issue by jldav1d** [remoo69/Compiler-Sheesh#34]
From screenshot ni greg
Code Snippet:
```
...
whilst(formula[i] != '\0')#
...
```
**_Error message_** :
_Can't Parse, Resolve Lexical Errors:
Line 76, Token 9: Invalid Charr Lenght_

**Comment by remoo69** [comment]
sige sige tignan ko

**Comment by remoo69** [comment]
![image](https://github.com/remoo69/Compiler-Sheesh/assets/121857724/57bc2939-e96a-4fe1-a834-66208be4640d)
added multi charr to constants
