### ISSUE TITLE
Incorrect error message for charr literal

### ISSUE THREAD

**Issue by jldav1d** [remoo69/Compiler-Sheesh#35]
Code Snippet:
`'A'+24 
`
**Error Message:**
Line 1, Token 1: No Closing Quote for 'A'+ 24 

**Expected:** 
Invalid Delimiter for ', '+'

**Comment by remoo69** [comment]
![image](https://github.com/remoo69/Compiler-Sheesh/assets/121857724/a9cea43f-486e-45bc-babb-1f0b0c232096)
pupush ko yung fix dito kaso di ko sure if magoopen up to ng new bugs
