### ISSUE TITLE
Issue with charr literal next to '==' or '!='

### ISSUE THREAD

**Issue by jldav1d** [remoo69/Compiler-Sheesh#36]
**1.)**
`'A'=='B' 
`
or
`'A'!='B' 
`

**Error Message:**
Line 1, Token 1: Invalid Null Delimiter for Charr ''', expected [',', ' ', '#', ')', '}', ':']
Line 1, Token 1: Invalid Delimiter [" ' "] for Identifier "A" , expected ['+', '-', '*', '/', '%', '<', '>', '!', '=', '!', '|', '&', ',', ' ', '#', '(', ')', '[', ']', '{', '.', ':']
Line 1, Token 1: Invalid Null Delimiter for Charr ''', expected [',', ' ', '#', ')', '}', ':']
Line 1, Token 2: Invalid Null Delimiter for Charr ''', expected [',', ' ', '#', ')', '}', ':']
Line 1, Token 2: Invalid Delimiter [" ' "] for Identifier "B" , expected ['+', '-', '*', '/', '%', '<', '>', '!', '=', '!', '|', '&', ',', ' ', '#', '(', ')', '[', ']', '{', '.', ':']
Line 1, Token 2: Invalid Null Delimiter for Charr ''', expected [',', ' ', '#', ')', '}', ':']

**Expected:** No Lexical Errors

**Comment by remoo69** [comment]
fix has been pushed
