### ISSUE TITLE
Invalid delim for )

### ISSUE THREAD

**Issue by jldav1d** [remoo69/Compiler-Sheesh#37]
**From New Test Cases**

**Expected:** No Error
Code:
```
sheesh(){
    whole x = 10#
    x += 1.1#
    x = seq_w[id()]#
}
```
**_Error Message_**
Can't Parse, Resolve Lexical Errors:
Line 4, Token 7: Invalid Delimiter for Symbol ')', '[]]', expected ['+', '-', '*', '/', '%', '<', '>', '!', '=', '!', '|', '&', ',', ' ', '#', ')', '}', '{', ':']

**Comment by remoo69** [comment]
fixed by a previous issue

![image](https://github.com/remoo69/Compiler-Sheesh/assets/121857724/a5b1da2d-64c7-431f-b1b1-2a0ef0e7c8d7)
