### ISSUE TITLE
Issue with (....)

### ISSUE THREAD

**Issue by jldav1d** [remoo69/Compiler-Sheesh#38]
## **From New Test Cases**

**Expected:** No Error

**Code:**
```
sheesh(){
    text name = "hello"#
    text f_name = name..."world"#
    text s_name = "first_name"...f_    name#
    text l_name = t_id()...id[0]#
}
```

**Error Message:**
Line 4, Token 5: Invalid Delimiter for Symbol '...', '[n]', expected ['"', '“', '"', '”', ' '] 
Line 5, Token 6: Invalid Delimiter for Symbol ')', '[.]', expected ['+', '-', '*', '/', '%', '<', '>', '!', '=', '!', '|', '&', ',', ' ', '#', ')', '}', '{', ':'] 
Line 5, Token 6: Invalid Delimiter for Symbol '...', '[i]', expected ['"', '“', '"', '”', ' ']

**Comment by remoo69** [comment]
ah pwede pala id HAHAAHAHAH

**Comment by remoo69** [comment]
weh pwede ba yung cases na yan

**Comment by remoo69** [comment]
fixed?

![image](https://github.com/remoo69/Compiler-Sheesh/assets/121857724/f521577b-b77d-4cca-9bc6-d70b8a4c25d5)

**Comment by jldav1d** [comment]
yep, allowed variables basta declared as `text`. Ty for the fix #bestprogrammer
