### ISSUE TITLE
allows uninitialized based (const)

### ISSUE THREAD

**Issue by jldav1d** [remoo69/Compiler-Sheesh#39]
## From New Test Cases

This issue applies to multiple based declaration.

**Expected:** Syntax Error
**Actual:** No Syntax Errors

**Code:**
```
based whole x#

sheesh(){
    yeet x#
}
```

**Comment by remoo69** [comment]
![image](https://github.com/remoo69/Compiler-Sheesh/assets/121857724/5e7db189-e93e-4063-9f52-261ec9ec274a)
