### ISSUE TITLE
update delim in the case of an array

### ISSUE THREAD

**Issue by 1202DREAMSCAPE** [remoo69/Compiler-Sheesh#4]
_**CASE 1: whole**_
<img width="405" alt="image" src="https://github.com/remoo69/Compiler-Sheesh/assets/88035813/0defa813-6089-4aef-a30d-60a4cdea82b0">

_**CASE 2: dec**_
<img width="543" alt="image" src="https://github.com/remoo69/Compiler-Sheesh/assets/88035813/f8e5a446-070a-460c-a6f5-9929a697e6df">

**Comment by remoo69** [comment]
case 1: fix implemented
case 2: fix implemented

both are untested
