### ISSUE TITLE
Issue with multiple based declaration

### ISSUE THREAD

**Issue by jldav1d** [remoo69/Compiler-Sheesh#40]
## From New Test Cases

**Expected:** No Error

Code:
```
based whole x = 10#
based text y = "hello"#
based sus k = cap#
based charr text l = 'A'#
based dec z = 1.0#

sheesh(){
    yeet x#
}
```

**Error Message:**
Line 2, Token 1: Unexpected "based" [based], expected -> ['def', 'sheesh']

**Comment by remoo69** [comment]
![image](https://github.com/remoo69/Compiler-Sheesh/assets/121857724/da0410f4-7b76-4bfa-bcd5-9c17d29a6e69)

may kulang lang na 1 line, di naeend yung const dec kaya error
