### ISSUE TITLE
syntax error when initializing a sequence dec

### ISSUE THREAD

**Issue by jldav1d** [remoo69/Compiler-Sheesh#41]
## From New Test Cases

**Expected**: No Syntax Errors

**Code:**
```
sheesh(){
    whole w[3] = {1,1,1}#
    text t[3] = {"first","second","third"}#
    dec d[3] = {1.0, 2.0, 3.0}#
    sus s[3] = {cap, nocap, cap}#
}
```

**Error Message:**
Line 2, Token 6: Unexpected "=" [=], expected -> ['#', ',', '[']

**Comment by remoo69** [comment]
dahil yan sa onedim sa mga vardec_tail

**Comment by remoo69** [comment]
![image](https://github.com/remoo69/Compiler-Sheesh/assets/121857724/4c07b660-e1e0-4876-8078-f174d1c23975)
