### ISSUE TITLE
Problem with sequence as parameters

### ISSUE THREAD

**Issue by jldav1d** [remoo69/Compiler-Sheesh#42]
**Expected:** No Error

**Code:**
```
def blank func(whole x[], whole y[][]){
    yeet#
}
sheesh(){
    yeet#
}
```    

**Error Message:**
Line 1, Token 14: Unexpected "[" [[], expected -> [',', ')']

**Comment by remoo69** [comment]
![image](https://github.com/remoo69/Compiler-Sheesh/assets/121857724/c894cb16-7bc7-4bcb-a1f6-8668784d17ba)

recently ko lang nakita inadd mo two d param HHAAHAHAH
