### ISSUE TITLE
Issue with arithmetic expressions as sequence index

### ISSUE THREAD

**Issue by jldav1d** [remoo69/Compiler-Sheesh#43]
**Code:**
**Expected:** No Syntax Errors
```
sheesh(){
    whole w[id+0] = {1,1,1}#
 }
```
**Actual**:
Line 2, Token 10: Unexpected "=" [=], expected -> ['#', ',', '[']

**Comment by remoo69** [comment]
ambiguous dahil may index din sa w_var_seq_tail and w_vardec_tail

**Comment by remoo69** [comment]
issue resolved by removing one_dim from w_vardec_tail
