### ISSUE TITLE
Issue with IDs in seq index

### ISSUE THREAD

**Issue by jldav1d** [remoo69/Compiler-Sheesh#44]
**Expected:** No Error

Code:
```
x[x[id(x[2])]] = 10# 
```
**Error Message:**
Line 3, Token 11: Invalid Delimiter for Symbol ')', '[]]', expected ['+', '-', '*', '/', '%', '<', '>', '!', '=', '!', '|', '&', ',', ' ', '#', ')', '}', '{', ':']

**Comment by remoo69** [comment]
added ] to delims
