### ISSUE TITLE
Compiler Crashes with "\"

### ISSUE THREAD

**Issue by 1202DREAMSCAPE** [remoo69/Compiler-Sheesh#5]
any that includes \ (backslash) invokes the compiler to crash

<img width="261" alt="image" src="https://github.com/remoo69/Compiler-Sheesh/assets/88035813/e4245aab-6538-4968-adc0-702f8bb4e66f">
<img width="250" alt="image" src="https://github.com/remoo69/Compiler-Sheesh/assets/88035813/542e5ec7-e8b9-4f67-8303-2dc12f2e2956">

**Comment by 1202DREAMSCAPE** [comment]
✅ accepts backslash enclosed in quotation marks

<img width="936" alt="image" src="https://github.com/remoo69/Compiler-Sheesh/assets/88035813/b15b0f88-d8e7-4895-ad2d-acf2d71b12a1">

**Comment by remoo69** [comment]
![image](https://github.com/remoo69/Compiler-Sheesh/assets/121857724/c118b452-bef2-4f78-aef8-bacedd2eea7c)

Fixed
