### ISSUE TITLE
type mismatch in up statement

### ISSUE THREAD

**Issue by jldav1d** [remoo69/Compiler-Sheesh#51]
**Issues:**
- type mismatch with written format specifier
- does not recognize positional arguments
- should check and match the number of format specifier and positional arguments

Example Code:
```
sheesh(){
    whole a = 2#
    up("$w", a)#   
}
```
```
sheesh(){
    up("$w $w $w $w")#
}
```
```
sheesh(){
    up("$w $w $w", 1)#
}
```

All the code above does not result in any expected semantic error.

**Comment by remoo69** [comment]
noted

**Comment by remoo69** [comment]
![image](https://github.com/remoo69/Compiler-Sheesh/assets/121857724/553ceefc-6509-426c-964e-cd08400447ba)

**Comment by remoo69** [comment]
close ko na since di na tayo self codegen
