### ISSUE TITLE
syntax issue with deins

### ISSUE THREAD

**Issue by jldav1d** [remoo69/Compiler-Sheesh#52]
**_Expected: No Syntax Errors
Actual: Syntax Error_**

Code:
```
sheesh(){
    kung(x>5){
        up("$w is greater than 5",x)#
    } 
    ehkung(cap){
        up("hello")#
    }
    deins{
        up("$w is less than 5",x)#
    }
}
``` 

Error message:
```Line 8, Token 2: Unexpected "{" [{], expected -> ['sus', 'charr', 'choose', 'text', 'Identifier', 'whole', '}', 'yeet', 'up', 'for', 'bet', 'dec', 'kung']```

**Comment by remoo69** [comment]
![image](https://github.com/remoo69/Compiler-Sheesh/assets/121857724/a22a4cf7-c8de-4710-93a3-7412d1bb218c)
grabe yung issue HAHAHAHA
typo lang
