### ISSUE TITLE
syntax issue with choose

### ISSUE THREAD

**Issue by jldav1d** [remoo69/Compiler-Sheesh#53]
Expected: No Syntax Error
Actual: Syntax Error

Code:
```
sheesh(){
    whole choice# 
    
    choose (choice) { 
        when '1':: 
            name = "hello" 
            felloff# 
        when '2':: 
            name = "bye" 
            felloff# 
        default :: 
            felloff#
    }
}
```

Error Message:
`Line 5, Token 4: Unexpected "EOL" [Newline], expected -> ['sus', 'charr', 'choose', 'felloff', 'text', 'Identifier', 'whole', 'yeet', 'up', 'for', 'bet', 'dec', 'kung']
`

**Comment by remoo69** [comment]
![image](https://github.com/remoo69/Compiler-Sheesh/assets/121857724/5a18858c-7495-4f6d-9332-d5ff4779f533)

close q n e2 bih,,,,
