### ISSUE TITLE
infinite loop when this input is entered in Lexer

### ISSUE THREAD

**Issue by jldav1d** [remoo69/Compiler-Sheesh#60]
Code:
`\\ `

This code produces an infinite loop, causing the whole compiler to crash

After tinkering with the source code using the VS code debugger with breakpoints. It may be a bug within the get_symbol function which doesn't return the remaining characters when the input is the code above.
```
def get_symbol(token):
    try:
        size=len(token)
        i=0
        symbol_buffer=''
        if token[i]=="#" and len(token)==1:
            return token, token.replace(token, '', 1)
        elif token[i] in const.all_symbols_nonop and token[i+1] in const.symbols_delims[token[i]]:
            symbol_buffer+=token[i]
            return token[i], token.replace(token[i], '', 1)
        elif token[i:2]=="::" and (len(token)==2 or token[i+2] in const.symbols_delims["::"]): 
                return "::", token.replace("::", '', 1)
        
    except IndexError:
        if token in const.grouping_symbols and None in const.symbols_delims[token]:
            return token, token.replace(token, '', 1)
```

**Comment by remoo69** [comment]
![image](https://github.com/remoo69/Compiler-Sheesh/assets/121857724/009bc6ac-033e-448b-ac35-088bff1d3a12)
the issue might've been because "\" isn't in any symbol list. I've put it into the "invalid_symbols" category. Will this conflict with anything? Do we use \ for anything other than withing text?

**Comment by jldav1d** [comment]
> Will this conflict with anything?

Nope, I don't think so.
> Do we use \ for anything other than withing text?

As far as i know, no. But "\\", based on our document, is used to display "\" onto the screen. So another thing to check if it works on the Lexer.

**Comment by jldav1d** [comment]
now resolved bruh.
