### ISSUE TITLE
Expected No Error (Undeclared Variable)

### ISSUE THREAD

**Issue by 1202DREAMSCAPE** [remoo69/Compiler-Sheesh#69]
![image](https://github.com/remoo69/Compiler-Sheesh/assets/88035813/9903c120-558d-4e21-89b3-cc1c8239c949)

CFG:

41	<sheesh_declaration>	→	sheesh() <reg_body>
50	<reg_body>	→	{<statement>}
42	<statement>	→	<single_statement><more_statement>
43	<single_statement>	→	<allowed_in_loop>
45	<allowed_in_loop>	→	<var_or_seq_dec>
59	<var_or_seq_dec>	→	<var_seq_common><var_seq_tail>#
61	<var_seq_common>	→	<seq_dtype>identifier
30	<seq_dtype>	→	whole
63	<var_seq_tail>	→	<vardec_tail>
64	<vardec_tail>	→	<variable_assign><more_vardec>
67	<variable_assign>	→	= <assign_value>
74	<assign_value>	→	<numeric_value><math_or_rel_expr>
39	<numeric_value>	→	whole_literal
222	<math_or_rel_expr>	→	λ
65	<more_vardec>	→	,identifier <vardec_tail>
64	<vardec_tail>	→	<variable_assign><more_vardec>
68	<variable_assign>	→	λ
66	<more_vardec>	→	λ
55	<more_statement>	→	<statement>
42	 <statement>	→	<single_statement><more_statement>
43	<single_statement>	→	<allowed_in_loop>
49	<allowed_in_loop>	→	identifier <id_tail>
54	<id_tail>	→	<assign_op><assign_value>#
90	<assign_op>	→	=
73	<assign_value>	→	<id_as_val><all_op>
69	<id_as_val>	→	identifier <id_val_tail>
72	<id_val_tail>	→	λ
217	<all_op>	→	<math_or_rel_expr>
220	<math_or_rel_expr>	→	<math_op>
223	<math_op>	→	<add_op><num_or_arithmexpr>
174	<add_op>	→	+
163	<num_or_arithmexpr>	→	<arithm_term><arithm_addtail>
164	<arithm_term>	→	<arithm_factor><arithm_mult_term>
165	<arithm_factor>	→	<numeric_value>
39	<numeric_value>	→	whole_literal
173	<arithm_mult_term>	→	λ
170	<arithm_addtail>	→	λ

**Comment by jldav1d** [comment]
Problem now resolved.

Terminal output of program above.
```
C:\Users\David\Downloads\sheesh#\Compiler-Sheesh>sheesh.exe                            
8 
```
