### ISSUE TITLE
cant read kung - deins // kung - ehkung -deins

### ISSUE THREAD

**Issue by 1202DREAMSCAPE** [remoo69/Compiler-Sheesh#71]
![image](https://github.com/remoo69/Compiler-Sheesh/assets/88035813/138809d7-f1c0-41f3-8523-e5c19379cff0)

error call
![image](https://github.com/remoo69/Compiler-Sheesh/assets/88035813/93a7e26c-4e80-4888-83f1-46dba143343f)

kung - ehkung - deins
![image](https://github.com/remoo69/Compiler-Sheesh/assets/88035813/e6e017e5-17aa-4015-b7ea-453ebc877f40)
_output is from prior checking, doesnt relate to the typed code_

**Comment by jldav1d** [comment]
issue now resolved.

Terminal output of the program above:
```
C:\Users\David\Downloads\sheesh#\Compiler-Sheesh>sheesh.exe                            
malay ko ba!
```
