### ISSUE TITLE
cannot read bet-whilst

### ISSUE THREAD

**Issue by 1202DREAMSCAPE** [remoo69/Compiler-Sheesh#72]
![image](https://github.com/remoo69/Compiler-Sheesh/assets/88035813/7b7a868f-5029-4ae0-93f5-925c147e4ba4)

I induced errors first to check if compiler reads the code properly then crashes at the moment it would read bet-whilst. the error message is from prior checking.

calls:
![image](https://github.com/remoo69/Compiler-Sheesh/assets/88035813/1e81eb78-2eb3-4863-be9a-679614400a26)

**Comment by remoo69** [comment]
ahhh conflict sa bet. resolved na ito now.
