### ISSUE TITLE
nocap and cap not recognized as reserved words + usage of sus results to crash

### ISSUE THREAD

**Issue by 1202DREAMSCAPE** [remoo69/Compiler-Sheesh#8]
<img width="929" alt="image" src="https://github.com/remoo69/Compiler-Sheesh/assets/88035813/2a906862-9b64-47bf-b487-cae20505b804">
<img width="933" alt="image" src="https://github.com/remoo69/Compiler-Sheesh/assets/88035813/80f41748-5b6a-4d11-8535-c27809f2bc62">

compiler unresponsive
<img width="933" alt="image" src="https://github.com/remoo69/Compiler-Sheesh/assets/88035813/ba2d933c-fd7b-4813-b51c-9b49e9d835b9">

**Comment by remoo69** [comment]
fixed
