### ISSUE TITLE
Lexer and Syntax Error for comma following a newline

### ISSUE THREAD

**Issue by jldav1d** [remoo69/Compiler-Sheesh#89]
**Expected:** No Error

**Example Code:**
```
sheesh(){
    whole x[5] = {1,
                           2,3,4,5}#
}
```
Error Message:
`Line 2, Token 9: Invalid Null Delimiter for Symbol ',', expected ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '1', '2', '3', '4', '5', '6', '7', '8', '9', '0', ' ', '(', '{', '"', "'"] `

**Comment by remoo69** [comment]
![image](https://github.com/remoo69/Compiler-Sheesh/assets/121857724/456833e8-c744-470f-b5f4-8c83a97aa53f)
so ito na valid?

**Comment by jldav1d** [comment]
salamuch boss romeo
