### ISSUE TITLE
Unexpected ( at line 2, expected sheesh

### ISSUE THREAD

**Issue by jldav1d** [remoo69/Compiler-Sheesh#9]
_Expected: NO ERROR_

**CODE:**```
```
whole add()#

sheesh(){
    whole result = add(3, 4)#
    up(""Result: %d\n"", result)#

}

whole add(whole a, whole b) {
    yeet a + b#
}"
```

**Comment by remoo69** [comment]
wala ata sa cfg yug () sa add?

**Comment by jldav1d** [comment]
function prototype yang add

**Comment by remoo69** [comment]
![image](https://github.com/remoo69/Compiler-Sheesh/assets/121857724/7ad0644c-bd00-42a2-841d-61b1aaa01b43)

but crashes with original input (two double-quotes)
