### ISSUE TITLE
 problem with division uli?? program 39

### ISSUE THREAD

**Issue by 1202DREAMSCAPE** [remoo69/Compiler-Sheesh#94]
![image](https://github.com/remoo69/Compiler-Sheesh/assets/88035813/fe78e4fb-f609-4171-8cea-d50467f1c09b)

pag tinanggal ko, nagrrun yung code--enclosing in parenthesis doesnt work too.

**Comment by 1202DREAMSCAPE** [comment]
-- has to do with assigning a value to the variable and including it in a mathematical operation

**Comment by jldav1d** [comment]
this works program works now, along side any program involving division

Terminal Output:
```
C:\Users\David\Downloads\sheesh#\Compiler-Sheesh>sheesh.exe                            
Enter weight (in kilogram): 12                                                         
Enter height (in meters): 34.5                                                         
Your BMI is 0.010082. You are classified as underweight.                               
C:\Users\David\Downloads\sheesh#\Compiler-Sheesh> 
```
